// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.59.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import "bridge_definitions.web.dart";
import 'dart:convert';
import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.web.dart';
export 'bridge_generated.web.dart';
import 'package:meta/meta.dart';

class FirstAidBotCorePlatform extends FlutterRustBridgeBase<FirstAidBotCoreWire>
    with FlutterRustBridgeSetupMixin {
  FirstAidBotCorePlatform(FutureOr<WasmModule> dylib)
      : super(FirstAidBotCoreWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;

// Section: api2wire

// Section: finalizer

}

// Section: WASM wire module

@JS('wasm_bindgen')
external FirstAidBotCoreWasmModule get wasmModule;

@JS()
@anonymous
class FirstAidBotCoreWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external FirstAidBotCoreWasmModule bind(dynamic thisArg, String moduleName);
  external dynamic /* void */ wire_hello_world(NativePortType port_);
}

// Section: WASM wire connector

class FirstAidBotCoreWire
    extends FlutterRustBridgeWasmWireBase<FirstAidBotCoreWasmModule> {
  FirstAidBotCoreWire(FutureOr<WasmModule> module)
      : super(WasmModule.cast<FirstAidBotCoreWasmModule>(module));

  void wire_hello_world(NativePortType port_) =>
      wasmModule.wire_hello_world(port_);
}
