version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/"
    target-branch: "dev"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "daily"
