version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    target-branch: "dev"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "app"
    target-branch: "dev"
    schedule:
      interval: "weekly"
