[workspace]
resolver = "2"

members = [
    "core",
    "bot",
    "app/rust"
]

[workspace.dependencies]
log = "0.4"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
anyhow = "1" 
serde = "1" 
