version: "3"

services:
  bot:
    build: 
      context: first_aid_bot_rust/
      args:
        - PROFILE=debug
    environment:
      - TELOXIDE_TOKEN=Миші з'їли
      # https://docs.google.com/spreadsheets/d/Миші з'їли/edit
      - SHEED_ID=Миші з'їли
      # - RUST_LOG=debug
    restart: always
    # ports:
    #   - 8081:8081
    depends_on:
      - "redis"

  redis:
    image: redis
    restart: always
    # ports:
    #   - 6379:6379
    volumes: 
      - cache:/bitnami/redis/data

volumes:
  cache:
    driver: local
