version: "3"

services:
  bot:
    build: 
      context: first_aid_bot_rust/
    environment:
      - TELOXIDE_TOKEN=5102517984:AAErbkUtig1PiOl1iSo3nAjzQ4MxV9w1gIU
      # https://docs.google.com/spreadsheets/d/1cO0sPRhIvt71J-iB313BeRfNXzXM0FjiQ4bDYmwddBQ/edit
      - SHEET_ID=1lPJgwtDRFul3klRKOrRDiF3ca5PjjUvFQmzF1ugOZUU
      # - RUST_LOG=debug
    restart: always
    # ports:
    #   - 8081:8081
    depends_on:
      - "redis"

  redis:
    image: redis
    restart: always
    # ports:
    #   - 6379:6379
    volumes: 
      - cache:/bitnami/redis/data
      - rdb:/data

volumes:
  cache:
    driver: local
  rdb:
    driver: local
