version: "3"

services:
  bot:
    build: 
      context: first_aid_bot_rust/
      dockerfile: Dockerfile.prod
    environment:
      - TELOXIDE_TOKEN=5253437681:AAES1RtIBXBanwaWvFk3vWaty-_LH1xYge0
      # https://docs.google.com/spreadsheets/d/1lPJgwtDRFul3klRKOrRDiF3ca5PjjUvFQmzF1ugOZUU/edit
      - SHEET_ID=1cO0sPRhIvt71J-iB313BeRfNXzXM0FjiQ4bDYmwddBQ
      - RUST_LOG=info
    restart: always
    # ports:
    #   - 8081:8081
    depends_on:
      - "redis"

  redis:
    image: redis
    restart: always
    # ports:
    #   - 6379:6379
    volumes: 
      - cache:/bitnami/redis/data
      - rdb:/data

volumes:
  cache:
    driver: local
  rdb:
    driver: local
