version: "3"

services:
  bot:
    build: first_aid_bot_rust/
    environment:
      - TELOXIDE_TOKEN=Миші з'їли
      # - RUST_LOG=debug
    restart: always
    # ports:
    #   - 8081:8081
    depends_on:
      - "redis"

  redis:
    image: redis
    restart: always
    # ports:
    #   - 6379:6379
    volumes: 
      - cache:/bitnami/redis/data

volumes:
  cache:
    driver: local
