version: "3"

services:
  bot:
    build: 
      context: first_aid_bot_rust/
      args:
        - PROFILE=release
    environment:
      - TELOXIDE_TOKEN=5253437681:AAES1RtIBXBanwaWvFk3vWaty-_LH1xYge0
    restart: always
    # ports:
    #   - 8081:8081
    depends_on:
      - "redis"

  redis:
    image: redis
    restart: always
    # ports:
    #   - 6379:6379
    volumes: 
      - cache:/bitnami/redis/data

volumes:
  cache:
    driver: local
