version: "3"

services:
  bot:
    build: 
      context: .
    environment:
      - TELOXIDE_TOKEN=Миші з'їли
      - SHEET_ID=Миші з'їли
      - RUST_LOG=info
    restart: always
    depends_on:
      - "redis"

  redis:
    image: redis
    restart: always
    volumes: 
      - cache:/bitnami/redis/data
      - rdb:/data

volumes:
  cache:
    driver: local
  rdb:
    driver: local
