[package]
name = "rust_lib_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
first_aid_bot_core = { path = "../../core" }
flutter_rust_bridge = "=2.0.0-dev.32"
anyhow = { workspace = true }
