[package]
name = "first_aid_bot_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Load the data
csv = "1.1"
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking"]}
regex = "1"

# Parse args
clap = { version = "3.1.2", features = ["derive"] }

# Telegram api
teloxide = { version = "0.7", features = ["macros", "auto-send"] }
log = "0.4"
pretty_env_logger = "0.4.0"
anyhow = "1"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
