[package]
name = "first_aid_bot_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Load the data
csv = "1.1"
bytes = "1.1.0"
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.11"}
regex = "1"

# Counting users
redis = { version = "0.21", features = ["tokio-comp"] }
futures = "0.3"

# Telegram api
teloxide = { version = "0.7", features = ["macros", "auto-send", "redis-storage", "bincode-serializer"] }
log = "0.4"
pretty_env_logger = "0.4.0"
anyhow = "1"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
