name: Build the library and test

on:
  workflow_call:
    inputs:
      release:
        type: boolean
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rs/toolchain@v1

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Download the table
        if: ${{ inputs.release }}
        run: curl -L "docs.google.com/spreadsheets/d/${{ secrets.SHEET_ID }}/gviz/tq?tqx=out:csv&sheet=Ukrainian" -o table.csv

      - uses: actions-rs/cargo@v1
        with:
          command: test

      - uses: actions/upload-artifact@v3
        if: ${{ inputs.release }}
        with:
          name: table
          path: table.csv

      - name: send telegram message on error
        if: ${{ failure() && inputs.release && inputs.deploy  }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            See error: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            The commit fails to build or tests have failed! 💣
