name: Build bot

on:
  workflow_call:
    inputs:
      release:
        type: boolean
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bot

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rs/toolchain@v1

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        if: ${{ inputs.release }}
        with:
          command: build
          args: --release

      - uses: actions-rs/cargo@v1
        if: ${{ !inputs.release }}
        with:
          command: build

      - name: Move binary
        run: mv target/*/first_aid_bot target

      - uses: actions/upload-artifact@v3
        with:
          name: executable
          path: target/first_aid_bot
