on:
  workflow_call:
    inputs:
      release:
        required: true
        type: boolean
      upload-artifact:
        required: true
        type: boolean

    secrets:
      SHEET_ID:
        required: true

jobs:
  build_and_test_bot:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Download the table
        if: inputs.release
        run: curl -L "docs.google.com/spreadsheets/d/${{ secrets.SHEET_ID }}/gviz/tq?tqx=out:csv&sheet=Ukrainian" -o table.csv

      - uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-expand
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: flutter_rust_bridge_codegen
          version: 2.0.0-dev.32
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Update bindings
        run: flutter_rust_bridge_codegen generate
        working-directory: app
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          RUST_LOG: info 
      - name: Test and build release
        if: inputs.release
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          RUST_LOG: info 
        run: cargo test --release -- --nocapture && cargo build --release

      - name: Test and build debug
        if: ${{ !inputs.release }}
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          RUST_LOG: info 
        run: cargo test -- --nocapture && cargo build

      - name: Move binary
        if: inputs.upload-artifact
        run: mv target/*/bot target

      - uses: actions/upload-artifact@v3
        if: inputs.upload-artifact
        with:
          name: executable
          path: target/bot
