on:
  workflow_call:
    inputs:
      # release:
      #   required: true
      #   type: boolean
      upload-artifact:
        required: true
        type: boolean

    secrets:
      SHEET_ID:
        required: true

jobs:
  build_flutter_apk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android, armv7-linux-androideabi, x86_64-linux-android, i686-linux-android
      - uses: Swatinem/rust-cache@v2
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: flutter_rust_bridge_codegen
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-ndk
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-expand
      - run: just && flutter build apk --release
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
      - uses: actions/upload-artifact@v3
        if: inputs.upload-artifact
        with:
          name: apk
          if-no-files-found: error
          path: app/build/app/outputs/flutter-apk/app-release.apk
