name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - "dev"
      - "main"

jobs:
  build_and_test_bot:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    environment: ${{ github.event.pull_request.base.ref }}

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Download the table
        if: github.event.pull_request.base.ref == 'main'
        run: curl -L "docs.google.com/spreadsheets/d/${{ secrets.SHEET_ID }}/gviz/tq?tqx=out:csv&sheet=Ukrainian" -o table.csv

      - name: Test and build release
        if: github.event.pull_request.base.ref == 'main'
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: cargo test --release && cargo build --release

      - name: Test and build debug
        if: github.event.pull_request.base.ref == 'dev'
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: cargo test && cargo build

      - name: Move binary
        run: mv target/*/bot target

      - uses: actions/upload-artifact@v3
        with:
          name: executable
          path: target/bot

      - uses: actions/upload-artifact@v3
        if: github.event.pull_request.base.ref == 'main'
        with:
          name: table
          path: table.csv

  deploy:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted]
    needs: [build_and_test_bot, build_flutter_apk]
    environment: ${{ github.event.pull_request.base.ref }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: executable
          path: bin/bot

      - uses: actions/download-artifact@v3
        if: github.event.pull_request.base.ref == 'main'
        with:
          name: table

      - name: Restart bot
        env:
          TELOXIDE_TOKEN: ${{ secrets.TELOXIDE_TOKEN }}
        run: |
          docker build -t first_aid_bot:${{ github.event.pull_request.base.ref == 'main' && 'main' || 'dev' }} .
          docker compose -f docker-compose_${{ github.event.pull_request.base.ref == 'main' && 'main' || 'dev' }}.yml -p ${{ github.event.pull_request.base.ref == 'main' && 'main' || 'dev' }}_bot up -d

  release:
    runs-on: ubuntu-latest
    needs: [build_and_test_bot, build_flutter_apk]
    if: github.event.pull_request.base.ref == 'main' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: table
      - uses: actions/download-artifact@v3
        with:
          name: executable
      - uses: actions/download-artifact@v3
        with:
          name: apk
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            app-release.apk
            table.csv
            first_aid_bot


  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event.pull_request.base.ref == 'main'

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: table

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        if: always() && github.event.pull_request.base.ref == 'main' && !contains(needs.*.result, 'failure')
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: table.csv
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            See changes: https://github.com/${{ github.repository }}/actions/runs/${{github.sha}}
            See error: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Successfully deployed! 🙆

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        if: always() && github.event.pull_request.base.ref == 'main' && contains(needs.*.result, 'failure')
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: table.csv
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            See changes: https://github.com/${{ github.repository }}/actions/runs/${{github.sha}}
            See error: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            The commit fails to build or tests have failed! 💣
