name: CI/CD dev

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"

concurrency:
  group: ${{ github.head_ref || github.run_id }}

jobs:
  build_and_deploy:
    uses: ./.github/workflows/CI_CD.yml
    with:
      release: false
      deploy: ${{ github.event_name == 'push' }}
      environment: test
    secrets: inherit
