name: Build and deploy dev

on:
  push:
    branches:
      - "dev"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_deploy:
    uses: .github/workflows/byild.yml
    with:
      release: false
      deploy: true
      environment: test
    secrets: inherit
