name: Build and deploy master

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:

  build_and_deploy:
    uses: .github/workflows/byild.yml
    with:
      release: true
      deploy: ${{ github.event_name != 'pull_request' }}
      environment: production
    secrets: inherit
