name: Build and deploy

on:
  push:
    branches: ["dev", "master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Build release
        if: github.ref == 'refs/heads/master'
        run: cargo build --release

      - name: Build debug
        if: github.ref == 'refs/heads/dev'
        run: cargo build

      - uses: actions/upload-artifact@v3
        with:
          name: executable
          path: target/*/first_aid_bot

      - name: send telegram message on push
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            See error: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            The commit fails to build! 💣

  save_table:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download the release table
        if: github.ref == 'refs/heads/master'
        run: curl -L "docs.google.com/spreadsheets/d/Миші з'їли/gviz/tq?tqx=out:csv&sheet=Ukrainian" -o table.csv

      - name: Download the test table
        if: github.ref == 'refs/heads/dev'
        run: curl -L "docs.google.com/spreadsheets/d/Миші з'їли/gviz/tq?tqx=out:csv&sheet=Ukrainian" -o table.csv

      - uses: actions/upload-artifact@v3
        with:
          name: table
          path: table.csv

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: executable

      - run: ls -R

  notify:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [deploy, save_table]

    steps:
      - uses: actions/download-artifact@v3
        if: github.ref == 'refs/heads/master'
        with:
          name: table

      - name: send telegram message on push
        if: success() && github.ref == 'refs/heads/master'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: table.csv
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            See changes: https://github.com/${{ github.repository }}/actions/runs/${{github.sha}}
            Successfully deployed main bot! 🙆

      - name: send telegram message on push
        if: success() && github.ref == 'refs/heads/dev'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            See changes: https://github.com/${{ github.repository }}/actions/runs/${{github.sha}}
            Successfully deployed test bot! 🙆
