name: Build, test

on:
  pull_request:
    branches:
      - "dev"
      - "main"

concurrency:
  group: ${{ github.base_ref  }}

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_bot:
    uses: ./.github/workflows/build_and_test_bot.yml
    with:
      release: ${{ github.base_ref == 'main' }}
      upload-artifact: true
    secrets:
      SHEET_ID: ${{ vars.SHEET_ID }}

  build_flutter_apk:
    uses: ./.github/workflows/build_flutter_apk.yml
    with:
      upload-artifact: true
    secrets:
      SHEET_ID: ${{ vars.SHEET_ID }}

  # It should wait untill all checks will pass
  auto-merge:
    needs: [build_and_test_bot, build_flutter_apk]
    runs-on: ubuntu-latest
    # if: github.base_ref == 'main'
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          # target: minor
          github-token: "${{ secrets.GITHUB_TOKEN }}"
