name: Build and deploy

on:
  push:
    branches: ["dev", "master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Install rust
      # - run: rustup toolchain install stable --profile minimal

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Build release
        if: github.ref == 'refs/heads/master'
        run: cargo build --release

      - name: Build debug
        if: github.ref == 'refs/heads/dev'
        run: cargo build

      - uses: actions/upload-artifact@v3
        with:
          name: executable
          path: target/*/first_aid_bot

  save_table:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download the release table
        if: github.ref == 'refs/heads/master'
        run: curl -L "docs.google.com/spreadsheets/d/Миші з'їли/gviz/tq?tqx=out:csv&sheet=Ukrainian" -o table.csv

      - name: Download the test table
        if: github.ref == 'refs/heads/dev'
        run: curl -L "docs.google.com/spreadsheets/d/Миші з'їли/gviz/tq?tqx=out:csv&sheet=Ukrainian" -o table.csv

      - uses: actions/upload-artifact@v3
        with:
          name: table
          path: table.csv

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: executable

      - run: ls -R
